package com.bykj.dao;

import cn.afterturn.easypoi.excel.annotation.Excel;

import java.io.Serializable;

public class StudentScore implements Serializable {

    private static final long serialVersionUID = 9128825689163506207L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.id
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.batch_id
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    @Excel(name = "考试批次" ,orderNum = "1")
    private Integer batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.student_id
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    @Excel(name = "学号" ,orderNum = "2")
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.name
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    @Excel(name = "姓名" ,orderNum = "3")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.sex
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    @Excel(name = "性别" ,orderNum = "4")
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.major
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    @Excel(name = "所属专业" ,orderNum = "5")
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    @Excel(name = "考试成绩" ,orderNum = "6")
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.score_status
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    @Excel(name = "成绩状态" ,orderNum = "7")
    private String scoreStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.violation_flag
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    @Excel(name = "违规标识" ,orderNum = "8")
    private Integer violationFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.status
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.bak1
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    private String bak1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.bak2
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    private String bak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.id
     *
     * @return the value of student_score.id
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.id
     *
     * @param id the value for student_score.id
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.batch_id
     *
     * @return the value of student_score.batch_id
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public Integer getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.batch_id
     *
     * @param batchId the value for student_score.batch_id
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.student_id
     *
     * @return the value of student_score.student_id
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.student_id
     *
     * @param studentId the value for student_score.student_id
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.name
     *
     * @return the value of student_score.name
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.name
     *
     * @param name the value for student_score.name
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.sex
     *
     * @return the value of student_score.sex
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.sex
     *
     * @param sex the value for student_score.sex
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.major
     *
     * @return the value of student_score.major
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.major
     *
     * @param major the value for student_score.major
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.score
     *
     * @return the value of student_score.score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.score
     *
     * @param score the value for student_score.score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.score_status
     *
     * @return the value of student_score.score_status
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public String getScoreStatus() {
        return scoreStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.score_status
     *
     * @param scoreStatus the value for student_score.score_status
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public void setScoreStatus(String scoreStatus) {
        this.scoreStatus = scoreStatus == null ? null : scoreStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.violation_flag
     *
     * @return the value of student_score.violation_flag
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public Integer getViolationFlag() {
        return violationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.violation_flag
     *
     * @param violationFlag the value for student_score.violation_flag
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public void setViolationFlag(Integer violationFlag) {
        this.violationFlag = violationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.status
     *
     * @return the value of student_score.status
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.status
     *
     * @param status the value for student_score.status
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.bak1
     *
     * @return the value of student_score.bak1
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.bak1
     *
     * @param bak1 the value for student_score.bak1
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.bak2
     *
     * @return the value of student_score.bak2
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.bak2
     *
     * @param bak2 the value for student_score.bak2
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    @Override
    public String toString() {
        return "StudentScore{" +
                "id=" + id +
                ", batchId=" + batchId +
                ", studentId=" + studentId +
                ", name='" + name + '\'' +
                ", sex='" + sex + '\'' +
                ", major='" + major + '\'' +
                ", score=" + score +
                ", scoreStatus='" + scoreStatus + '\'' +
                ", violationFlag=" + violationFlag +
                ", status=" + status +
                ", bak1='" + bak1 + '\'' +
                ", bak2='" + bak2 + '\'' +
                '}';
    }
}