package com.bykj.mapper;

import com.bykj.dao.StudentScore;
import com.bykj.dao.StudentScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    long countByExample(StudentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    int deleteByExample(StudentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    int insert(StudentScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    int insertSelective(StudentScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    List<StudentScore> selectByExample(StudentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    StudentScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") StudentScore record, @Param("example") StudentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    int updateByExample(@Param("record") StudentScore record, @Param("example") StudentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    int updateByPrimaryKeySelective(StudentScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Wed May 08 15:56:44 CST 2019
     */
    int updateByPrimaryKey(StudentScore record);
}